services:
  go-scaffo:
    build:
      context: ./
      dockerfile: Dockerfile
    image: go-scaffo-img
    container_name: go-scaffo
    volumes:
      - .:/go/src
    env_file:
      - ./.env
    tty: true
    stdin_open: true