services:
  go-scaffo:
    build:
      context: ./
      dockerfile: Dockerfile
    image: go-scaffo-img
    container_name: go-scaffo
    volumes:
      - .:/go/app
    env_file:
      - ./.env
    ports:
      - '8100:8100'
    tty: true
    stdin_open: true